# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/z1528/Desktop/SEA_S7/Tests/Game/Project/Project.srcs/sources_1/ip/Box_G_Rom/Box_G_Rom.xci
# IP: The module: 'Box_G_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/z1528/Desktop/SEA_S7/Tests/Game/Project/Project.srcs/sources_1/ip/Box_G_Rom/Box_G_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Box_G_Rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/z1528/Desktop/SEA_S7/Tests/Game/Project/Project.srcs/sources_1/ip/Box_G_Rom/Box_G_Rom.xci
# IP: The module: 'Box_G_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/z1528/Desktop/SEA_S7/Tests/Game/Project/Project.srcs/sources_1/ip/Box_G_Rom/Box_G_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Box_G_Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
